# Kubernetes： kube-state-metrics
groups:
  - name: 节点已长时间未就绪
    rules:
      - alert: 节点已长时间未就绪
        expr: kube_node_status_condition{condition="Ready",status="false"} == 1
        for: 5m
        labels:
          severity: 严重
        annotations:
          summary: "节点已长时间未就绪 (实例 {{ $labels.node }})"
          description: "节点 {{ $labels.node }} 已长时间未就绪。"

  - name: Kubernetes Pod OOMKilled
    rules:
      - alert: Kubernetes 容器OOMKilled
        expr: sum(kube_pod_container_status_terminated_reason{reason="Error"}) by (namespace, pod, container,datacenter,instance) > 0
        for: 1m
        labels:
          severity: 严重
        annotations:
          summary: "Kubernetes 容器OOMKilled (实例 {{ $labels.instance }})"
          description: "Kubernetes 容器 {{ $labels.container }} 在 {{ $labels.namespace }} 命名空间中发生了 OOMKilled 事件。"

  - name: Kubernetes Pod JobFailed
    rules:
      - alert: Kubernetes 容器JobFailed
        expr: sum(kube_pod_container_status_terminated_reason{reason="Error"}) by (namespace, pod, container,datacenter,instance) > 0
        for: 1m
        labels:
          severity: 严重
        annotations:
          summary: "Kubernetes 容器JobFailed (实例 {{ $labels.instance }})"
          description: "Kubernetes 容器 {{ $labels.container }} 在 {{ $labels.namespace }} 命名空间中发生了 JobFailed 事件。"

  - name: Kubernetes Pod 状态异常
    rules:
      - alert: Kubernetes Pod 状态异常
        expr: sum(kube_pod_status_phase{phase=~"Pending|Failed|Unknown"}) by (namespace, pod, container,datacenter,instance) > 0
        for: 1m
        labels:
          severity: 严重
        annotations:
          summary: "Kubernetes Pod 状态异常 (实例 {{ $labels.instance }})"
          description: "Kubernetes Pod {{ $labels.pod }} 在 {{ $labels.namespace }} 命名空间中出现了异常状态。"

  - name: Kubernetes pod 崩溃循环
    rules:
      - alert: Kubernetes pod 崩溃循环
        expr: increase(kube_pod_container_status_restarts_total[1m]) > 3
        for: 1m
        labels:
          severity: 严重
        annotations:
            summary: "Kubernetes pod 崩溃循环 (实例 {{ $labels.instance }})"
            description: "Kubernetes pod {{ $labels.pod }} 在 {{ $labels.namespace }} 命名空间中发生了崩溃循环。"
